### ISSUE TITLE
Transport Error while running it against AWS hosted ElasticSearch Service

### ISSUE THREAD

**Issue by aamirmushtaq** [cldcvr/elasticsearch-s3-backup#2] opened 2017-08-24 10:08 UTC
I am getting the following error while running it against the AWS hosted ElasticSearch Service. 

> root@ip-10-12-135-180:/home/ec2-user# python test.py -m backup
> /usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py:59: UserWarning: Connecting to https://search-qaelasticsearch-lcufjovhtwj5tlppyhhy5tx6am.us-east-1.es.amazonaws.com:443 using SSL with verify_certs=False is insecure.
>   'Connecting to %s using SSL with verify_certs=False is insecure.' % self.base_url)
> /usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   SNIMissingWarning
> /usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecurePlatformWarning
> /usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> 
> [INFO] ES client info: {u'cluster_name': u'044818063657:qaelasticsearch', u'tagline': u'You Know, for Search', u'version': {u'lucene_version': u'5.5.0', u'build_hash': u'72aa8010df1a4fc849da359c9c58acba6c4d9518', u'number': u'2.3.2', u'build_timestamp': u'2016-11-14T15:59:50Z', u'build_snapshot': False}, u'name': u'Destroyer'}
> /usr/local/lib/python2.7/dist-packages/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecurePlatformWarning
> /usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
>   InsecureRequestWarning)
> 
> 
> [ERROR] Unexpected error: TransportError(500, u'repository_exception', u'[kenobilogs] failed to create repository')
> 
> 
> [All done!]

**Comment by nonbeing** [comment] 2017-08-24 14:29
Thanks for bringing this up, @aamirmushtaq, will look into this.

**Comment by nonbeing** [comment] 2017-09-21 14:18
@aamirmushtaq : we could not repro this error - working just fine for our AWS-ES domain.

Observed the following `urllib3` problems from your stack trace:

```
InsecurePlatformWarning
InsecureRequestWarning
...
You can upgrade to a newer version of Python to solve this.
```

Please see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings for resolving these issues. 

From the above link:
> This happens on Python 2 platforms that have an outdated ssl module. These older ssl modules can cause some insecure requests to succeed where they should fail and secure requests to fail where they should succeed. Follow the [pyOpenSSL](https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2)  guide to resolve this warning.

Lastly, the code in the `aws-ES-service` branch has now been updated to work for Python3 also - please retry with Python3 as this should probably resolve the matter for you.

**Comment by nonbeing** [comment] 2017-10-10 04:15
Closing since "Cannot reproduce" and it works just fine.

**Closed as completed by nonbeing** 2017-10-10 04:15 UTC
